### ISSUE TITLE
你们不翻译`auto_examples/`里那些东西嘛？

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/sklearn-doc-zh#230]
这里是示例部分的一些翻译，不全：

<https://github.com/htygithub/machine-learning-python>

**Comment by chenyyx** [comment]
非常感谢啊，飞龙大佬，不是不翻译那些 example，我们打算这些 examples 先翻译几个。如果大佬们觉得很好的话，那其他的大佬有兴趣的就直接翻译，并在相应的 example 的 py 代码中添加自己的注释，便于以后其他的读者阅读，现在已经翻译了几个 examples，还在进行中..... :)
