### ISSUE TITLE
原文存疑

### ISSUE THREAD

**Issue by noeagles** [apachecn/sklearn-doc-zh#285]
http://scikit-learn.org/stable/tutorial/basic/tutorial.html#learning-and-predicting

中一句

It now must be fitted to the model, that is, it must learn from the model. 

Classifiers should learn from the data instead of the model which is only a set o f assumptions that  help form the classifier.

**Comment by chenyyx** [comment]
好的，大佬，我看一下

**Comment by chenyyx** [comment]
好的，谢谢大佬，这儿是翻译的时候有一些问题，马上修改。谢谢

**Comment by chenyyx** [comment]
我懂了你的意思，大佬，刚开始我以为是翻译有问题（但是翻译刚才确实有点问题，不是适应应该是拟合模型），后来了解了你的意思。这里说， clf 必须拟合 model，必须从 model 中学习，后面的一句话，你可能没有注意到， This is
done by passing our training set to the ``fit`` method. 这句话，它说，从 model 中学习是通过将 training set 传到 fit 方法中实现的。这个学习本质上仍然是从数据中学习，而不是上面所说的model。不知道回答在没在点子上，期待反馈，谢谢大佬

**Comment by wizardforcel** [comment]
我觉得原文多了个 **from**，**learn the model** 表示习得模型，是没问题的。
