### ISSUE TITLE
any idea to translate mxnet doc?

### ISSUE THREAD

**Issue by NonvolatileMemory** [apachecn/sklearn-doc-zh#295]
mxnet is an open source deep learning framework?
Do you want to translate its doc?

**Comment by chenyyx** [comment]
Yes, our organization intends to translate this framework for the next step. Welcome to join us! come on dalao ^_^

**Comment by NonvolatileMemory** [comment]
@chenyyx  now I am busy working on IJCAI(DDL:1/28) and SIGIR(DDL:1/28), after that I will have adequate time, really want to wort with you!

**Comment by chenyyx** [comment]
@NonvolatileMemory   Okay, I'm looking forward to working with you, it must be very happy~~~
