### ISSUE TITLE
宏平均和微平均

### ISSUE THREAD

**Issue by lumialalala** [apachecn/sklearn-doc-zh#326]
![image](https://user-images.githubusercontent.com/10848940/44946892-4d699700-ae37-11e8-923a-4e898f1132e0.png)

macro-averaged是否应该翻译成宏平均？

**Comment by loopyme** [comment]
感谢反馈！目前该问题已在[新版本](http://sklearn.apachecn.org/#/docs/32?id=_3311-%E5%B8%B8%E8%A7%81%E5%9C%BA%E6%99%AF-%E9%A2%84%E5%AE%9A%E4%B9%89%E5%80%BC)中修复
