### ISSUE TITLE
图片链接错误

### ISSUE THREAD

**Issue by muyuan11** [apachecn/sklearn-doc-zh#327]
我按照 readme 中制作本地的静态html版本
首先 这个版本的doc ，限制了必须 0.19.0 sklearn 才有效， 其他高版本，会报错，特别是 0.20的报错更多。估计和很多 api修改有关。然后我降级到指定版本 0.19

make html 报告 需要一个 gallery  readme.txt文件？clone下来文件中没有，我只好随便复制了一个。之后 倒是可以创建 静态页面了，但是一大堆warning ，应该都是图片相关的。 进入文档后，发现大部分图片链接都是失效额。

能否提供合理的gallery  readme.txt文件？ 保证图片链接正确

**Comment by wizardforcel** [comment]
框架已更换。请：

```
npm install -g gitbook
gitbook build
```
