### ISSUE TITLE
链接失效404

### ISSUE THREAD

**Issue by johnniesong** [apachecn/sklearn-doc-zh#332]
http://sklearn.apachecn.org/#/docs/72
中的链接失效404

http://sklearn.apachecn.org/#/../../auto_examples/exercises/plot_cv_diabetes.html?id=sphx-glr-auto-examples-exercises-plot-cv-diabetes-py

**Comment by johnniesong** [comment]
http://sklearn.apachecn.org/#/docs/69
页面内全部连接404

**Comment by FesonX** [comment]
自动生成的链接全部404http://sklearn.apachecn.org/#/generated/sklearn.neighbors.KernelDensity.html?id=sklearn.neighbors.kerneldensity

**Comment by loopyme** [comment]
感谢反馈！目前该类问题已在新版本中基本修复,如果仍发现存在链接404,欢迎再次反馈.
