### ISSUE TITLE
中文文档支持搜索吗？

### ISSUE THREAD

**Issue by potoo0** [apachecn/sklearn-doc-zh#333]
就是怎么搜索某个函数或者其他关键字的文档呢？

**Comment by loopyme** [comment]
感谢反馈！目前暂不支持搜索，若需搜索，一个可行的解决方法是使用github的[仓库内搜索](https://github.com/apachecn/scikit-learn-doc-zh/search?q=%E8%81%9A%E7%B1%BB&unscoped_q=%E8%81%9A%E7%B1%BB)．

**Comment by wizardforcel** [comment]
已添加

**Comment by potoo0** [comment]
好的，谢谢。
