### ISSUE TITLE
网页貌似挂掉了

### ISSUE THREAD

**Issue by daidai21** [apachecn/sklearn-doc-zh#334]

**Comment by wizardforcel** [comment]
<http://www.17ce.com/site/http/20190127_bfc8e5f0221611e998204d480bb0e4b0:1.html>

**Comment by daidai21** [comment]
![image](https://user-images.githubusercontent.com/36124626/51799502-24212b80-225c-11e9-854a-b38cbb2bbfb8.png)

。。。
