### ISSUE TITLE
中文文档网站无法打开？

### ISSUE THREAD

**Issue by Qipccc** [apachecn/sklearn-doc-zh#335]
http://sklearn.apachecn.org/
这个网站无法访问
如下图
![](https://raw.githubusercontent.com/Qipccc/learning-note/master/image/%E6%8D%95%E8%8E%B7.PNG)

**Comment by wizardforcel** [comment]
的确有些地方无法访问

http://www.17ce.com/site/http/20190208_e67ea4502b5311e998204d480bb0e4b0:1.html

改成 https 就行了
