### ISSUE TITLE
打开index.html时网页显示now loading...

### ISSUE THREAD

**Issue by jxhuliqun138** [apachecn/sklearn-doc-zh#340]
now loading... 
一直卡在这， 
ailearning 里面的index.html打开时没有这个问题，
doc相关的git 库都显示  "now loading... ", 打不开

**Comment by HelloWorldBeginner** [comment]
我这也是打不开，而且很多图片显示不出来

**Comment by loopyme** [comment]
静态网站是使用jekyll来生成的,如果需要在本地预览网站,请[配置jekyll环境](http://jekyllcn.com/docs/home/)

**Comment by wizardforcel** [comment]
http://www.17ce.com/site/http/20190605_2466bef0874411e99098ed35cce8fdda:1.html

这是国内的测速报告。

请咨询你所在地区的运营商谢谢。
