### ISSUE TITLE
在线阅读方式对应的模型评估部分页面显示404，麻烦你们看下

### ISSUE THREAD

**Issue by 645187919** [apachecn/sklearn-doc-zh#341]

**Comment by loopyme** [comment]
感谢反馈！目前该问题已在[新版本](http://sklearn.apachecn.org/#/docs/32?id=_33-%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0--%E9%87%8F%E5%8C%96%E9%A2%84%E6%B5%8B%E7%9A%84%E8%B4%A8%E9%87%8F)中修复
