### ISSUE TITLE
【0.19.X】贡献者名单

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/sklearn-doc-zh#354]
**翻译者(人人皆大佬~):**

* [@wangyangting](https://github.com/wangyangting)（那伊抹微笑）
* [@jiangzhonglian](https://github.com/jiangzhonglian)（片刻）
* [@chenyyx](https://github.com/chenyyx)（Joy yx）
* [@survivingME](https://github.com/survivingME)（Trembleguy）
* [@mtobeiyf](https://github.com/mtobeiyf)（Fing）
* [@Leon-Jin](https://github.com/Leon-Jin)（Leon晋）
* [@X1aoFang](https://github.com/X1aoFang)（X1aoFang）
* [@loverollcat](https://github.com/loverollcat)（loverollcat）
* [@helloheshee](https://github.com/helloheshee)（helloheshee）
* [@SkyDreamStart](https://github.com/SkyDreamStart)（SkyDreamStart）
* [@HazekiahWon](https://github.com/HazekiahWon)（Hazekiah Wang）
* [@201419](https://github.com/201419)（tree）
* [@busesese](https://github.com/busesese)（wenyi）
* [@chrzc](https://github.com/chrzc)（changzhicheng）
* [@Zoctan](https://github.com/Zoctan)（Zoctan）
* [@JanzenLiu](https://github.com/JanzenLiu)（Janzen_Liu）
* [@charleschou520](https://github.com/charleschou520)（charleschou520）
* [@zhangqiking](https://github.com/zhangqiking)（BigBird）
* [@mikechengwei](https://github.com/mikechengwei)（Mike）
* [@wodekwan](https://github.com/wodekwan)（wodekwan）
* [@sehriff](https://github.com/sehriff)（sehriff）
* [@Kdotm](https://github.com/Kdotm)（kngines）
* [@patientman](https://github.com/patientman)（YuanMingLiu）
* [@DamonDay](https://github.com/DamonDay)（DamonDay）
* [@cszhangbo](https://github.com/cszhangbo)（cszhangbo）
* [@XingxGit](https://github.com/XingxGit)（XingxGit）
* [@KrokYin](https://github.com/KrokYin)（KrokYin）
* [@yw10](https://github.com/yw10)（Andrew Yao）
* [@GlassyWu](https://github.com/GlassyWu)（glassy）
* [@PrivateRookie](https://github.com/PrivateRookie)（PrivateRookie）
* [@linweijiang](https://github.com/linweijiang)（linweijiang）
* [@jiaqiangbandongg](https://github.com/jiaqiangbandongg)（jiaqiangbandongg）
* [@supportingvector](https://github.com/supportingvector)（supportingvector）
* [@stealthsMrs](https://github.com/stealthsMrs)（stealthsMrs）
* [@lhwlhw90](https://github.com/lhwlhw90)（lhwlhw90）
* [@sheepmen](https://github.com/sheepmen)（羊三）
* [@guohao916](https://github.com/guohao916)（guohao_dm）
* [@Daemon-ser](https://github.com/Daemon-ser)（csu_hgq）
* [@wangxiancai](https://github.com/wangxiancai)（BWM-蜜蜂）
* [@夜神月](@qq760514101)（夜神月）
* [@liyangbit](https://github.com/liyangbit)（Lemon）
* [@XuJianzhi](https://github.com/XuJianzhi)（XuJianzhi）

**校验者(人人皆大佬~)**（现在还不齐全，贡献者大佬们可随意修改）

* [@weiyd](https://github.com/weiyd)（尔了个达）
* [@FontTian](https://github.com/FontTian)（FontTian）
* [@XuJianzhi](https://github.com/XuJianzhi)（XuJianzhi）
* [@caopeirui](https://github.com/caopeirui)（Veyron C）
* [@HelloSilicat](https://github.com/HelloSilicat)（Jialiang Pei）
* [@AnybodyHome](https://github.com/AnybodyHome)（loop）
* [@RyanZhiNie](https://github.com/RyanZhiNie)（Zhi Nie）
* [@zehuichen123](https://github.com/zehuichen123)（loveSnowBest）
* [@hlxstc](https://github.com/hlxstc)（Jokers）
* [@NellyLuo](https://github.com/NellyLuo)（NellyLuo）
* [@yuezhao9210](https://github.com/yuezhao9210)（Yue Zhao）
* [@why2lyj](https://github.com/why2lyj)（Snow Wong）
* [@pan8664716](https://github.com/pan8664716)（pan8664716）
* [@xrj](https://github.com/xrj)（xrj）
* [@qvduoduo1997](https://github.com/qvduoduo1997)（qvduoduo1997）
* [@marsjhao](https://github.com/marsjhao)（Zhang Junhao）
* [@tiantian1412](https://github.com/tiantian1412)（tiantian1412）
* [@sheepmen](https://github.com/sheepmen)（羊三）
* [@wangyangting](https://github.com/wangyangting)（那伊抹微笑）
* [@jiangzhonglian](https://github.com/jiangzhonglian)（片刻）
* [@chenyyx](https://github.com/chenyyx)（Joy yx）
* [@mikechengwei](https://github.com/mikechengwei)（Mike）
* [@wangxiancai](https://github.com/wangxiancai)（BWM-蜜蜂）
* [@busesese](https://github.com/busesese)（wenyi）
* [@GlassyWu](https://github.com/GlassyWu)（glassy）
* [@wodekwan](https://github.com/wodekwan)（wodekwan）
* [@gbyy422990](https://github.com/gbyy422990)（Bin GAO）
* [@charleschou520](https://github.com/charleschou520)（charleschou520）
* [@DataMonk2017](https://github.com/DataMonk2017)（Jeremy Zheng）
* [@Lixu518](https://github.com/Lixu518)（Mysry）
* [@linxiamen](https://github.com/linxiamen)（YUNCHUAN LIN）
* [@llcing](https://github.com/llcing)（Mayouji）
* [@KyrieHee](https://github.com/KyrieHee)（HeYun）
* [@ziepenn](https://github.com/ziepenn)（ziepenn）
* [@FAN0521](https://github.com/FAN0521)（FAN0521）
* [@Daemon-ser](https://github.com/Daemon-ser)（csu_hgq）
* [@shaoyy147](https://github.com/shaoyy147)（Y.Shao）
* [@Kdotm](https://github.com/Kdotm)（kngines）
* [@chrzc](https://github.com/chrzc)（changzhicheng）
* [@ywujudy](https://github.com/ywujudy)（ywujudy）
* [@污剑客](https://github.com/apachecn)（污剑客）
* [@爱吹牛逼的小明](https://github.com/apachecn)（爱吹牛逼的小明）
* [@JanzenLiu](https://github.com/JanzenLiu)（Janzen_Liu）
* [@Ecauchy](https://github.com/Ecauchy)（Ecauchy）

**Comment by jiangzhonglian** [comment]
0.18版本：[http://cwiki.apachecn.org/pages/viewpage.action?pageId=10030181](http://cwiki.apachecn.org/pages/viewpage.action?pageId=10030181)

**Comment by xuxiaoxia1129** [comment]
牛逼
