### ISSUE TITLE
epub链接404

### ISSUE THREAD

**Issue by jiahe224** [apachecn/sklearn-doc-zh#388]
另外就是具体算法的使用找不到对应处，比如https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html，是因为没翻译这块儿吗

**Comment by loopyme** [comment]
- [epub](https://github.com/apachecn/sklearn-doc-zh/raw/epub/sklearn_0.21.3_2019_12_13.epub)已更新
- `API Reference` 目前还没有翻译,只翻译了`User Guide`和`Tutorial`
