### ISSUE TITLE
公式无法正确渲染

### ISSUE THREAD

**Issue by ketra21** [apachecn/sklearn-doc-zh#400]
![image](https://user-images.githubusercontent.com/38323732/78095475-aa5d7280-7409-11ea-806a-73ca07d3deb9.png)
链接：https://sklearn.apachecn.org/docs/0.21.3/2.html

**Comment by loopyme** [comment]
我尝试使用我们在[docs/0.21.3/22.md](https://github.com/apachecn/sklearn-doc-zh/blob/master/docs/0.21.3/22.md)文件里的做法来修复这个公式,但依旧没有成功渲染

在[docs/0.21.3/2.md](https://github.com/apachecn/sklearn-doc-zh/blob/master/docs/0.21.3/2.md)中公式被错误渲染成`{% math %}...{% endmath %}`而不是正确的`<span class="katex"><span class="katex-mathml"><math>...</math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.68333em;"></span>`

我尚不清楚问题原因,但该issue所述问题在其他文件中不可复现,也许是Katex或自动部署Gitbook时出现问题.

**Comment by loopyme** [comment]
问题已定位,在 a4c8b916d4ee2df0f586145eb685c034622b0da0 中引入`{%raw%}...{% endraw %}`来避免特殊字符渲染错误,但同时也阻止了渲染公式

考虑到`{%raw%}...{% endraw %}`被广泛使用,也许我们需要使用`{% endraw %}...{%raw%}`来包裹公式片段
