### ISSUE TITLE
md格式问题-【教程·处理文本数据】

### ISSUE THREAD

**Issue by ketra21** [apachecn/sklearn-doc-zh#427]
多了一对代码顿号，如图。
系统：Windows 10，浏览器：Chrome 版本 86.0.4240.75（正式版本） （64 位）
链接：[https://sklearn.apachecn.org/docs/master/59.html](https://sklearn.apachecn.org/docs/master/59.html)
![image](https://user-images.githubusercontent.com/38323732/96988827-712c5180-1557-11eb-8ac2-f576205f3f78.png)

**Comment by jiangzhonglian** [comment]
谢谢，已经修正
