### ISSUE TITLE
标点符号错误-【教程·处理文本数据】

### ISSUE THREAD

**Issue by ketra21** [apachecn/sklearn-doc-zh#428]
如图，
1、多了一个下划线“_”
2、句号"."应为全角句号"。"
链接:[https://sklearn.apachecn.org/docs/master/59.html](https://sklearn.apachecn.org/docs/master/59.html)
![image](https://user-images.githubusercontent.com/38323732/96989351-22cb8280-1558-11eb-9d20-ea95fd8b2a29.png)

**Comment by jiangzhonglian** [comment]
谢谢，已经修正
