### ISSUE TITLE
1.10.6. 决策树算法: ID3, C4.5, C5.0 和 CART 中错别字

### ISSUE THREAD

**Issue by chaos-wan** [apachecn/sklearn-doc-zh#438]
决策树发展到其最大尺寸，然后通常利用剪枝来提高树对未知数据的“泛华”能力，引号处应为泛化

**Comment by jiangzhonglian** [comment]
方便的话，可以提交一下 Pull requests

不方便的话，也可以提供一下页面地址和问题截图

**Comment by jiangzhonglian** [comment]
不方便的话，也可以提供一下页面地址和问题截图
