### ISSUE TITLE
gitee pages挂了，scikitlearn.com.cn要求关注公众号才能使用

### ISSUE THREAD

**Issue by e-yi** [apachecn/sklearn-doc-zh#439]
可以重新挂下gitee pages或者提供一个其他的国内访问方式？scikitlearn.com.cn的做法令人不齿，我建议从readme里面去掉它。

**Comment by e-yi** [comment]
![image](https://github.com/apachecn/sklearn-doc-zh/assets/20715359/0fc4a6a7-20d2-4da8-8344-c8955989c1df)

**Comment by jiangzhonglian** [comment]
我们的网站： <https://sklearn.apachecn.org>

**Comment by e-yi** [comment]
嗯，是的，不过我建议修改readme

**Comment by jiangzhonglian** [comment]
已经删除了该网站，谢谢建议
